### ISSUE TITLE
wp-gistpen so good idea, but little problem please help me.

### ISSUE THREAD

**Issue by clh021** [mAAdhaTTah/writing#6]
`{"code":"rest_invalid_param","message":"\u65e0\u6548\u53c2\u6570\uff1ablobs","data":{"status":400,"params":{"blobs":""}}}`

I found your blog through “WordPress < -> GitHub sync” this plugin, then saw this project, I think your idea is very good, but maybe because the version of wordpress is continuously updated, this plugin has a little problem, ask you please.

**Comment by mAAdhaTTah** [comment]
Could you share what you were doing at the time you got this error?

**Comment by clh021** [comment]
Sorry, this "WP-Gistpen" plugin is used in the latest version of Wordpress.
Open page "New Gistpen", input all field and save request sending.
The api response return json like this:
`{"code":"rest_invalid_param","message":"\u65e0\u6548\u53c2\u6570\uff1ablobs","data":{"status":400,"params":{"blobs":""}}}`
